version: "2"
run:
  build-tags:
    - dbtest
linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - godox
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
  settings:
    godox:
      keywords:
        - FIXME
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "^(ST1005|QF1003|QF1001):"

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      module-path: github.com/simplesurance/baur/v5
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/simplesurance/baur/v5
