run:
  build-tags:
    - dbtest

linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - errorlint
    - gocritic
    - godox
    - gofumpt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nosprintfhostport
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - typecheck
    - unconvert
    - usetesting
    - unused
    - usestdlibvars

linters-settings:
  goimports:
    local-prefixes: github.com/simplesurance/baur/v5
  godox:
    keywords:
      - FIXME
  gofumpt:
    module-path: github.com/simplesurance/baur/v5
    extra-rules: true
